### ISSUE TITLE
Resize enhancement

### ISSUE THREAD

**Issue by dexhek** [xCONFLiCTiONx/StickyPad#1]
I think the StickyPad could be more useful if its  resizable... ResizeMode="CanResizeWithGrip" may be a solution. Also, for a state of the art app, it should also remember the  Width and Height on restart.. :D

**Comment by xCONFLiCTiONx** [comment]
I haven't worked on this project for a long time and didn't think anyone would ever use it so I've abandoned it. I would like to give you the opportunity to clone it and you can fix it on your end, if you like. Else, I'll get to it as soon as I can. Please let me know.
